### ISSUE TITLE
Example usage of MT_linear_regression

### ISSUE THREAD

**Issue by forCharlie** [bibliolytic/MTlearning#1]
Hi,dear bibliolytic,do you mind give me an example of MT_linear_regression ? Thank you in advance!

**Comment by vinay-jayaram** [comment]
Hi Charlie, MT_linear_regression should work exactly the same as MT_linear, except that it doesn't require that there be only two values in the y vector, and that it returns real-valued outputs. If you give me a few days, I'll write an example into the test script as well

**Comment by forCharlie** [comment]
That would be great,thanks! and another question:do all the task's inputs have to be same structural(I mean the dimension number and sample number)?

**Comment by vinay-jayaram** [comment]
Dimension number yes, but sample number no

**Comment by forCharlie** [comment]
I see,thanks!

**Comment by forCharlie** [comment]
hi,still wait for that example,cause I have tried changing the linear example as you said ,but it kept throwing errors.

**Comment by vinay-jayaram** [comment]
Example is added, and you're right the function was not implemented properly. Thanks for noticing and letting me know!
